[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyidebug"
version = "1.0.0"
authors = [
  { name="Natanael Quintino", email="natanael.quintino@ipiaget.pt" },
]
description = "Module that allows you to interactively debug your code."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/NaelQuin/pyidebug"
"Bug Tracker" = "https://github.com/NaelQuin/pyidebug/issues"
